version: "3"
services:

  postgres:
    image: postgres
    container_name: db_postgresql
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: productAPI
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - .data/postgres:/var/lib/postgresql/data

  api:
    build: .
    container_name: api_product
    ports:
      - "8080:8080"
